const MenuData = [
    {   id:1,
        photo1:"./images/p1.jpg" ,
        photo2:"./images/p2.jpeg",
        dishName:"pasta",
        rate:"10",
        desc:"Lorem ipsum or random text may be used"
     },
    {   id:2,
        photo1:"./images/n1.jpg",
        photo2:"./images/n2.jpg",
        dishName:"Noodles",
        rate:"9.5",
        desc:"Lorem ipsum or random text may be used",
    },
   
    {   id:3,
        photo1:"./images/m2.jpg",
        photo2:"./images/m1.jpg",
        dishName:"Veg Biryani",
        rate:"20",
        desc:"Lorem ipsum or random text may be used", 
    },

   {   id:4,
        photo1:"./images/b1.jpg",
        photo2:"./images/b2.jpg",
        dishName:"Chiken Biryani",
        rate:"25",
        desc:"Lorem ipsum or random text may be used",
    },
    {   id:5,
        photo1:"./images/v1.jpg",
        photo2:"./images/v2.jpg",
        dishName:"Veg Thali",
        rate:"40",
        desc:"Lorem ipsum or random text may be used"
     },
    {   id:6,
        photo1:"./images/br3.jpg",
        photo2:"./images/br1.jpg",
        dishName:"Breakfast",
        rate:"8",
        desc:"Lorem ipsum or random text may be used",
    },
   
    {   id:7,
        photo1:"./images/d1.jpeg",
        photo2:"./images/d2.jpg",
        dishName:"Donuts",
        rate:"5",
        desc:"Lorem ipsum or random text may be used", 
    },

   {   id:8,
        photo1:"./images/r2.jpg",
        photo2:"./images/r1.jpg",
        dishName:"Rasmalai",
        rate:"10",
        desc:"Lorem ipsum or random text may be used",
    },
    {   id:9,
        photo1:"./images/o1.jpeg",
        photo2:"./images/o2.jpg",
        dishName:"Oreo Shake",
        rate:"3",
        desc:"Lorem ipsum or random text may be used", 
    },

   {   id:10,
        photo1:"./images/f1.jpg",
        photo2:"./images/f2.jpg",
        dishName:"Faluda",
        rate:"5",
        desc:"Lorem ipsum or random text may be used",
    },
]
export default MenuData;